/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EDU_gatech_cc_is_newton_Newton */

#ifndef _Included_EDU_gatech_cc_is_newton_Newton
#define _Included_EDU_gatech_cc_is_newton_Newton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    make_resident
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EDU_gatech_cc_is_newton_Newton_make_1resident
  (JNIEnv *, jobject);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    make_free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EDU_gatech_cc_is_newton_Newton_make_1free
  (JNIEnv *, jobject);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    open_newton
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_EDU_gatech_cc_is_newton_Newton_open_1newton
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    read_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EDU_gatech_cc_is_newton_Newton_read_1frame
  (JNIEnv *, jobject);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    getNumVis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_EDU_gatech_cc_is_newton_Newton_getNumVis
  (JNIEnv *, jobject, jint);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    getX
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_EDU_gatech_cc_is_newton_Newton_getX
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    getY
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_EDU_gatech_cc_is_newton_Newton_getY
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     EDU_gatech_cc_is_newton_Newton
 * Method:    getArea
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_EDU_gatech_cc_is_newton_Newton_getArea
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
